language: bash

sudo: required

services:
  - docker

before_install:
  - docker pull hashicorp/terraform:0.11.14
  - docker pull wata727/tflint:latest

script:
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.11.14 validate -check-variables=false
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.11.14 fmt -write=false -diff=true -check=true
  - docker run --rm -v $(pwd):/data --workdir=/data -t hashicorp/terraform:0.11.14 get
  - docker run --rm -v $(pwd):/data --workdir=/data -t wata727/tflint:latest --var-file=test.tfvars
